### ISSUE TITLE
Bật app nếu có tin nhắn thoại.

### ISSUE THREAD

**Issue by JustinBeBoy** [JustinBeBoy/zalo_auto#1]
• Bật tắt : tính năng tự động mở tin nhắn thoại

Nếu bật : 
- (đứng ở ngoài Zalo) Khi có tin nhắn thoại => đưa người dùng vào group chát
==> Có **nút trả lời nhanh nổi**, nếu người dùng bấm vào nút đó sẽ tự động **vuốt trả lời tin nhắn gần nhất**, Hiển Thị Trong 30s. Đợi đến khi màn hình tắt , tự trở về trang chủ điện thoại.
• (đứng ở Trong Zalo) , có tin nhắn thoại mới lúc này sẽ không kéo người dùng sang nhóm chát khác nữa.

Nếu Tắt : 
•khi có tin nhắn Thoại => hiển thị thông báo : bạn có tin nhắn thoại
________
Bật / Tắt : nút trả lời nhanh nổi 
• khi bật : nút trả lời nhanh luôn hiển thị khi màn hình ở trong app zalo
• Khi tắt : nút trả lời nhanh ko hiện liên tục mà chỉ xuất hiện khi có tin nhắn thoại ở trên.

**Comment by DucTV995** [comment]
• Nếu đã trong ứng dụng zalo , có tin nhắn thoại mới lúc bày sẽ không kéo người dùng sang nhóm khác nữa.

**Comment by DucTV995** [comment]
![Screenshot_2024-10-19-22-06-04-238_com.zing.zalo.jpg](https://github.com/user-attachments/assets/cc1e0bdb-1539-4944-892b-c3e94033400e)

**Comment by JustinBeBoy** [comment]
@DucTV995  cái này xong chưa nếu xong thì close đi nhé em

**Comment by DucTV995** [comment]
cái này thay đổi khác hoàn toàn. close đi a

**Comment by DucTV995** [comment]
close
