### ISSUE TITLE
Thêm tương tác chạm văn bản

### ISSUE THREAD

**Issue by DucTV995** [JustinBeBoy/zalo_auto#11]
Trong bảng thông báo được bật lên .... nếu click chạm vào văn bản thì mở nhóm zalo đó và không có hành động thêm. Nếu chạm vào chữ "nhận" thì bao gồm các phản hồi : rung ngắn, mở nhóm zalo và thực hiện hành vi trả lời...

**Comment by frank269** [comment]
resolved
