### ISSUE TITLE
Lỗi thông báo khi trong câu có nhiều hơn 1 dấu ":"

### ISSUE THREAD

**Issue by DucTV995** [JustinBeBoy/zalo_auto#20]
Ví dụ câu sau : Hôm nay 12:00 xe 5c Nha Trang - Da Lat giao 800

sau dấu ":" đầu tiên sẽ nhận tất cả nội dung văn bản . nếu văn bản có số lượng ký tự nhiều hơn 5 và ít hơn 350

**Comment by JustinBeBoy** [comment]
xong
