### ISSUE TITLE
Giao diện Cơ Bản của App

### ISSUE THREAD

**Issue by DucTV995** [JustinBeBoy/zalo_auto#34]
Biểu Tượng Cài đặt : 
![giao dien cai dat](https://github.com/user-attachments/assets/bcd0db44-7cc2-4eca-b4e9-76df7631df3f)
_________________________________________
Bật : tương đương với tick chọn app zalo , lắng nghe thông báo từ zalo.
______________________________
Chức năng Tắt/bật 
- Bỏ qua thông báo xin , đổi
- Bỏ qua thông báo xe 7 chỗ 
===> Được ghép với code 
![màn hình free](https://github.com/user-attachments/assets/4d76f814-2ceb-4120-89e3-cc203ba8d7d5)

**Comment by JustinBeBoy** [comment]
duplicate
