### ISSUE TITLE
Giao diện nâng cao 

### ISSUE THREAD

**Issue by DucTV995** [JustinBeBoy/zalo_auto#35]
![màn hình đã trả phí](https://github.com/user-attachments/assets/431cac4f-8a6e-43b3-a2e7-47da65d90bfa)
Ghép code vào các cài đặt trong phần nâng cao :

- Đọc thông báo cuốc : Trạng thái bao gồm Tắt / Bật và Tốc độ đọc
- Nút trả lời nhanh trong zalo : là nút nổi được hiển thị liên tục khi người dùng ở app zalo
- Nội dung trả lời : văn bản được người dùng nhập vào
- Mở zalo khi có tin nhắn thoại : là tính năng tự động mở app zalo khi có tin nhắn thoại mới.
- Tự động nhận cuốc : có trạng thái tắt / bật
Thêm hoặc bớt các từ khóa trong cài đặt

**Comment by JustinBeBoy** [comment]
duplicate
