### ISSUE TITLE
Thêm cài đặt số s hiển thị thông báo cho người dùng ở phần nâng cao 

### ISSUE THREAD

**Issue by JustinBeBoy** [JustinBeBoy/zalo_auto#47]
@DucTV995 d

Có nên thêm số s hiển thị thông báo cho ngừoi dùng trong phần nâng cao hay không ?
Nếu có thêm yêu cầu design thêm

**Comment by DucTV995** [comment]
> @DucTV995 d
> 
> Có nên thêm số s hiển thị thông báo cho ngừoi dùng trong phần nâng cao hay không ? Nếu có thêm yêu cầu design thêm


Không cần thêm số Giây trong cài đặt . Để mặc định 15s ạ
